- name: Preparar y comprimir la carpeta
        run: |
          # Creamos un directorio temporal para preparar los archivos
          mkdir build
          
          # Copiamos todo el contenido (excluyendo lo que no debe ir) hacia la carpeta 'build'
          rsync -av --exclude='.git' --exclude='.github' --exclude='build' --exclude='mapa-pai-co.zip' ./ build/
          
          # Entramos en la carpeta 'build' y comprimimos todo su contenido
          # El punto '.' al final significa "comprime todo lo que hay aquí"
          cd build && zip -r ../mapa-pai-co.zip .